[build]
builder = "nixpacks"
buildCommand = """
cd backend
python -m pip install --upgrade pip
pip install -r requirements.txt
"""

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10