"""Create initial tables

Revision ID: 2ce3d36697a6
Revises: 84d773b574ba
Create Date: 2025-02-10 19:58:09.431518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce3d36697a6'
down_revision: Union[str, None] = '84d773b574ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pizzas_id'), 'pizzas', ['id'], unique=False)
    op.create_index(op.f('ix_pizzas_name'), 'pizzas', ['name'], unique=True)
    op.create_table('toppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toppings_id'), 'toppings', ['id'], unique=False)
    op.create_index(op.f('ix_toppings_name'), 'toppings', ['name'], unique=True)
    op.create_table('pizza_toppings',
    sa.Column('pizza_id', sa.Integer(), nullable=True),
    sa.Column('topping_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza_toppings')
    op.drop_index(op.f('ix_toppings_name'), table_name='toppings')
    op.drop_index(op.f('ix_toppings_id'), table_name='toppings')
    op.drop_table('toppings')
    op.drop_index(op.f('ix_pizzas_name'), table_name='pizzas')
    op.drop_index(op.f('ix_pizzas_id'), table_name='pizzas')
    op.drop_table('pizzas')
    # ### end Alembic commands ###
